@c cha-datatypes.texi
@c Created by Laurence D. Finston (LDF) Thu Jul 15 14:51:42 CEST 2010

@node Data type reference
@chapter Data type reference
@cindex Data type reference

@menu
* X.509 Certificate Data Types::
@end menu

@node X.509 Certificate Data Types
@section X.509 Certificate Data Types

!! START HERE:  This list isn't complete.  LDF 2010.07.15.

Data types for X.509 certificates are declared in the following files
in the directory @file{[...]/gnutls/lib/}:

@c 

@itemize @w{}

@item
@file{auth_cert.h}

@item 
@file{gnutls_cert.h}

@item 
@file{gnutls_cert.h}

@item
@file{gnutls_auth.h}

@item
@file{auth_dh_common.h}

@item
@file{x509/x509_int.h}

@item
@file{openpgp/openpgp_int.h}
@end itemize

Declared in @file{auth_cert.h}:

!! START HERE:  LDF 2010.07.15.

@c /home/lfinsto/gnutls_dev/gnutls/lib/auth_cert.h

@dtindex gnutls_certificate_credentials_st, struct

@c typedef struct gnutls_certificate_credentials_st






